In [ ]:
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns



df = pd.read_csv('car_fuel_efficiency.csv')


df.columns = df.columns.str.lower().str.replace(' ', '_')

strings = list(df.dtypes[df.dtypes == 'object'].index)


for col in strings:
    df[col] = df[col].str.lower().str.replace(' ', '_')


df = df[['engine_displacement',
'horsepower',
'vehicle_weight',
'model_year',
'fuel_efficiency_mpg']]

df.head()
df.dtypes

for col in df.columns:
    print(col)
    print(df[col].unique()[:6])
    print(df[col].nunique())
    print()

%matplotlib inline
sns.histplot(df.fuel_efficiency_mpg, bins=100)

df.isnull().sum()







In [ ]:
median_value = df['horsepower'].median()
print(f"The median of 'horsepower' is: {median_value}")

The median of 'horsepower' is: 149.0


In [ ]:
n = len(df)

n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

n

n_val, n_test, n_train

df.iloc[[10, 0, 3, 5]]

df_val = df.iloc[n_train:n_train+n_val]
df_test = df.iloc[n_train+n_val:]

idx = np.arange(n)

df_zero = df
df_mean = df

df_zero.horsepower = df.horsepower.fillna(0)
df_mean.horsepower = df.horsepower.fillna(df.iloc[idx[:n_train]].horsepower.mean())


np.random.seed(42)
np.random.shuffle(idx)

df_train_zero = df_zero.iloc[idx[:n_train]]
df_train_mean = df_mean.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train+n_val]]
df_test = df.iloc[idx[n_train+n_val:]]
df_train_zero.head()
df_train_mean.head()

len(df_train_zero), len(df_train_mean), len(df_val), len(df_test)

df_train_zero = df_train_zero.reset_index(drop=True)
df_train_mean = df_train_mean.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train_zero = np.log1p(df_train_zero.fuel_efficiency_mpg.values)
y_train_mean = np.log1p(df_train_mean.fuel_efficiency_mpg.values)
y_val = np.log1p(df_val.fuel_efficiency_mpg.values)
y_test = np.log1p(df_test.fuel_efficiency_mpg.values)

del df_train_zero['fuel_efficiency_mpg']
del df_train_mean['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

len(y_train_zero), len(y_train_mean)

df_train_zero.iloc[10]

xi = [240, 159, 2916.987921, 2021]
w0 = 0
w = [0.01, 0.01, 0.0001, 0.0001]

def linear_regression(xi):
    n = len(xi)

    pred = w0

    for j in range(n):
        pred = pred + w[j] * xi[j]

    return pred

linear_regression(xi)

np.expm1(4.4837987921)

np.log1p(87.57049530949243)





np.float64(4.4837987921)

In [ ]:
#Vector form

def dot(xi, w):
    n = len(xi)
    
    res = 0.0
    
    for j in range(n):
        res = res + xi[j] * w[j]
    
    return res

def linear_regression(xi):
    return w0 + dot(xi, w)

w_new = [w0] + w

w_new

def linear_regression(xi):
    xi = [1] + xi
    return dot(xi, w_new)

linear_regression(xi)

x1  = [1, 250, 139, 2116, 2020]
x2  = [1, 270, 179, 2916, 2010]
x10 = [1, 210, 159, 2516, 2022]

X = [x1, x2, x10]
X = np.array(X)
X

def linear_regression(X):
    return X.dot(w_new)

linear_regression(X)


array([4.3036, 4.9826, 4.1438])

In [ ]:
#Train linear regression

def train_linear_regression(X, y):
    pass

X = [
    [250, 135, 2126, 2020],
    [270, 174, 2936, 2010],
    [210, 150, 2546, 2022],
    [220, 133, 2156, 2020],
    [230, 179, 2966, 2012],
    [240, 159, 2576, 2022],
    [250, 137, 2186, 2023],
    [260, 172, 2996, 2010],
    [280, 151, 2506, 2022]
]

X = np.array(X)
X

array([[ 250,  135, 2126, 2020],
       [ 270,  174, 2936, 2010],
       [ 210,  150, 2546, 2022],
       [ 220,  133, 2156, 2020],
       [ 230,  179, 2966, 2012],
       [ 240,  159, 2576, 2022],
       [ 250,  137, 2186, 2023],
       [ 260,  172, 2996, 2010],
       [ 280,  151, 2506, 2022]])

In [ ]:
# ones = np.ones(X.shape[0])
# ones
# X = np.column_stack([ones, X])
# X


In [ ]:
y = [11, 12, 10, 9, 8, 29, 8, 9, 10]

XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
w_full = XTX_inv.dot(X.T).dot(y)
w0 = w_full[0]
w = w_full[1:]

w0,w


(np.float64(-0.016661777095872805),
 array([ 0.90016006, -0.04375928, -0.00562528]))

In [ ]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w_full = XTX_inv.dot(X.T).dot(y)
    
    return w_full[0], w_full[1:]

train_linear_regression(X, y)

(np.float64(-2005.3921283646032),
 array([ 0.00458104,  0.90435302, -0.03168192,  0.96998229]))